### ISSUE TITLE
Feature Request: parameter highlighting in functions

### ISSUE THREAD

**Issue by jwerts** [thomaslindstrom/no-caffeine-syntax#15]
First off - I love this color scheme.

Second - not sure how difficult this would be but it'd be awesome if the function parameters were highlighted differently from other variables and maintained that highlighting through the function.

For instance:
![image](https://cloud.githubusercontent.com/assets/674057/10439579/d3c65456-7108-11e5-9780-9bd501cbed22.png)

The function parameters ```query``` and ```selectionMode``` would maintain their yellow coloring (or some other color specific to function parameters)  throughout the function so it's easy to tell that they were function parameters and not variables created within the function.

Python Tools for Visual Studio does this with Python and it's really helpful.

**Comment by thomaslindstrom** [comment]
Thanks! Unfortuneately, though, Atom does not parse function parameters in the function body. This color scheme is just that, a color scheme – so there's “nothing” I can do to. 

However, if you open this issue up on https://github.com/atom/language-javascript, they could probably help you with this, and then I'll implement it if it lands!
