### ISSUE TITLE
No colors in the syntax

### ISSUE THREAD

**Issue by Yaco** [thomaslindstrom/no-caffeine-syntax#20]
Hi! I am big fan of your theme :p

Since some days ago I dont see colors in my syntax. Reinstalled the theme, but the problem is still there. Also tryed cleaning atom cache files and other similar stuff.

I am running atom 1.12.7.

Any clue? Thx!

**Comment by thomaslindstrom** [comment]
Could you try updating your Atom version?

**Comment by Yaco** [comment]
Yeap! I updated to 1.14.3 and works again.

Thanks man!
