### ISSUE TITLE
Visually conflicts with linter-ui-default

### ISSUE THREAD

**Issue by pbarbiero** [thomaslindstrom/no-caffeine-syntax#22]
https://github.com/steelbrain/linter-ui-default

The border line causes quite a jarring look when `linter-ui-default` is enabled. Many of the other syntax themes do not have this issue, and instead put the border properly on the right of all the gutters.

![untitled](https://user-images.githubusercontent.com/20247733/28130448-4508e8dc-66fc-11e7-994e-5e08df7561f0.png)

Atom 1.18.0
Using atom one dark theme

**Comment by thomaslindstrom** [comment]
Looks a bit jarring, I agree.

**Comment by pbarbiero** [comment]
Closing this, as I think just changing the config for `linter-ui-default` setting `Gutter Highlights Position` to left fixed it, and I think still looks fine.
