### ISSUE TITLE
json files customization

### ISSUE THREAD

**Issue by kostadinnm** [thomaslindstrom/no-caffeine-syntax#23]
Hi there.
I'm trying out some dark themes and went on using no-caffeine-syntax along with [numix-dark-ui](https://github.com/nephitejnf/numix-dark-ui). I was wondering whether a little better highlighting could be added for json-files?! Here's how I tweaked the light one I use[spectrum-ligth-syntax](https://github.com/adcoulter/spectrum-light-syntax) to alternate the highlighting only for the leaf-nodes of the json structure(the '>' symbol is conflicting css-code and markdown):
[silly gist](https://gist.github.com/kostadinnm/6a1d0ddc3a535204045cc2613b589ed7)
And here's a comparison:
![no_caffeine_atom_theme_suggestion](https://user-images.githubusercontent.com/18436405/40855911-9ab119ee-65de-11e8-83b6-788e0f7a0207.jpg)
Note that [spectrum-ligth-syntax](https://github.com/adcoulter/spectrum-light-syntax) is highlighting non-string json-keys as errors as well.

I think it'll be a good addition, especially for package.json files that are utilized by the node-community. I'm not much into styling, otherwise would've make a better, if not direct suggestion on how that improvement could be done :)
Cheers,
Kostadin

**Comment by thomaslindstrom** [comment]
Hey, @kostadinnm! Are you saying you want styling of erroneous JSON syntax? Or maybe different styling of keys and values? Or both?

**Comment by kostadinnm** [comment]
For now, I think It'd be good if just the values(the leaf-nodes of a json structure) be different color. Something like what I did with the aforementioned theme. That would benefit most, as it's far more clear what values one's using in their package.json files. Maybe you should do it only for the package.json as other json-files may have other needs.

**Comment by thomaslindstrom** [comment]
Look for this in `0.19.0`! Let me know if there is anything else.

**Comment by kostadinnm** [comment]
Charming!
I have no other suggestions - I just customized my comments NOT to be italic and use a warmer chrome-theme, but I see you prefer a seti-like one.
Skol,
Kostadin

**Comment by thomaslindstrom** [comment]
Yeah, I use [seti-ui](https://github.com/jesseweed/seti-ui). It works well with `no-caffeine-syntax`!
