### ISSUE TITLE
Line number display overlaps with tabbar

### ISSUE THREAD

**Issue by Leonick** [thomaslindstrom/no-caffeine-syntax#7]
When a document gets long enough to scroll the column on the left side showing line numbers will overlap the tabbar.

![capture](https://cloud.githubusercontent.com/assets/2903631/7196992/96b8588e-e4db-11e4-944d-95c7d3fa7fe4.PNG)

Does not happen with other syntax Themes. 
I've tried with both Atom Light and One Light as UI Themes and it happens with both.

**Comment by thomaslindstrom** [comment]
Thanks, I was assuming this was an UI theme issue, but it's not.

**Comment by thomaslindstrom** [comment]
Please update `no-caffeine-syntax` to `v0.11.0` and try again! :

**Comment by Leonick** [comment]
That fixed it. Awesome!

**Comment by thomaslindstrom** [comment]
I made a mistake and the cursor went misaligned, but it's fixed in `v0.11.1`. Thanks!
